types:
  - build
  - deploy

before_script:
  - 'rm -f ci-host.zip'
  - 'apt-get --yes install zip'

build:
  type: build
  only:
    - master
  script:
    - 'zip -r ci-host.zip .'

deploy:
  type: deploy
  only:
    - master
  script:
    - 'ci-deploy $CI_PROJECT_ID'
