types:
  - build
  - deploy

build:
  type: build
  only:
    - master
  script:
    - 'rm -f ci-host.zip'
    - 'zip -r ci-host.zip . -x *.git*'
    - 'ls'

deploy:
  type: deploy
  only:
    - master
  script:
    - 'apt-get --yes install zip'
    - 'ls'
    - 'ci-deploy $CI_PROJECT_ID'
